### PR TITLE
MVP Candidate

### PR DESCRIPTION
**Pull request by ChrisSavoie**
Alright, pretty sure this meets the needs of what we discussed. Wireframes were filled in, and designed in-browser on the go.
- [x] Color and provide design fill for all wireframe elements
- [x] Home and Project template
- [x] Finalize brand colors

Dev effort included all of the following.
- [x] Logo, top menu, front page content areas for copy and/or graphics
- [x] Projects section on home page linking to project pages
- [x] Project pages template (i.e. CTMs, Trade Manager)
- [x] Partners (Dash, Bitt, TigoCTM, Coinapult, Crypto Capital, etc.)
- [x] Contact Form

I predict the project template may need to be addressed again at some point to establish a very specific templated style but I'd like to see some content for one of those pages to know what I'm working with in the future.

### CODE REVIEW

**Comment by ChrisSavoie** [comment]
@isysd Ta Daaaa!

**Comment by isysd** [comment]
@ChrisSavoie thank you! Crazy ass day, and I pulled an all nighter last night. Plan to test this before sleeping, but no promises.

@indieinc @d3brouille halp! This needs to be live on Wed..

**Comment by ChrisSavoie** [comment]
@isysd There are a few pages that have dummy repeated content in them. Specifically:
- The [about/partners](https://github.com/ChrisSavoie/gitguild_website/tree/master/content/partners) require a short paragraph of content written.
- Any projects you'd like to feature on the homepage will pull content from [content/projects](https://github.com/ChrisSavoie/gitguild_website/tree/master/content/projects)
- All content in [content/post](https://github.com/ChrisSavoie/gitguild_website/tree/master/content/post) could be deleted or set `draft = true` to save as example posts.

Perhaps this is a job for @glenkow 
- Note: [content/about.md](https://github.com/ChrisSavoie/gitguild_website/blob/master/content/about.md) is currently unused. This can be linked to later from [config.toml](https://github.com/ChrisSavoie/gitguild_website/blob/master/config.toml)

**Comment by isysd** [comment]
@ChrisSavoie I believe there's a missing directory.

ERROR: 2016/08/15 Unable to find static directory for theme gitguild in /tmp/gitguild_website/themes/gitguild/static

**Comment by glenkow** [comment]
Yes I will write the content / copy for this.

**Comment by ChrisSavoie** [comment]
Oops. @isysd the theme is a repository of itself. I didn't realize cloning the website repo wouldn't clone the theme repo that is contained within.

```
git clone https://github.com/ChrisSavoie/gitguild_website.git
git clone https://github.com/ChrisSavoie/hugo-gitguild-theme gitguild_website/themes/gitguild
cd gitguild_website
hugo serve
```

If you clone both repositories and put the theme in the themes directory in a folder called "gitguild" it'll work properly.

**Comment by isysd** [comment]
@ChrisSavoie what you're looking for is a git submodule.

```
cp -fR themes/gitguild themes/gitguildbackup
git rm themes/gitguild
git submodule add https://github.com/ChrisSavoie/hugo-gitguild-theme themes/gitguild
```

Will fix this up. I would do for you, but it's on your private branch and probably easier for you to just run the commands. :bow:

**Comment by ChrisSavoie** [comment]
@isysd fix applied in https://github.com/ChrisSavoie/gitguild_website/commit/fd7279c26f663a08b5c7f089e90cf4cc77ec62c5

**Comment by isysd** [comment]
Really love this so far! :+1: The universal bootstrap theme looks like a really helpful addition, and the seed content looks great. Going to merge this to make it easier for @glenkow to work on the copy, and for us to document any remaining issues individually.

**Pull request merged**
